"""add_new_table

Revision ID: 7ed8caad3497
Revises: 07377cfbec8f
Create Date: 2024-03-09 19:44:58.585653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed8caad3497'
down_revision: Union[str, None] = '07377cfbec8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'likes')
    # ### end Alembic commands ###
